version: "2" # According to documentation, required to adjust maintainability checks

plugins:
  # disable Rubocop at CodeClimate, it cannot read the shared config from
  # the /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml file
  rubocop:
    enabled: false

  duplication:
    enabled: true
    exclude_patterns:
      - "test/"
    config:
      languages:
      - ruby

checks:
  method-lines:
    config:
      threshold: 30 # Same limit than YaST's Rubocop config

  method-count:
    config:
      threshold: 50 # FIXME: temporarily raised to an absurdly high value to postpone the discussion
