# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Redundant returns add legibility for developers used to other languages
Style/RedundantReturn:
  Enabled: false

# Don't complain on definitions like this. We like question marks!
# def some_boolean?; some_boolean; end
TrivialAccessors:
  ExactNameMatch: true

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Metrics/LineLength:
  Max: 105
