# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Redundant returns add legibility for developers used to other languages
Style/RedundantReturn:
  Enabled: false

# Don't complain on definitions like this. We like question marks!
# def some_boolean?; some_boolean; end
TrivialAccessors:
  ExactNameMatch: true

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Metrics/LineLength:
  Max: 105

# FIXME: Let's consider this temporary code and be permissive with the lack of
# documentation
Style/Documentation:
  Exclude:
    - 'src/lib/storage/extensions.rb'
    - 'src/lib/expert_partitioner/ui_extensions.rb'
    - 'src/lib/expert_partitioner/icons.rb'
    - 'src/lib/expert_partitioner/tab_views/*'
    - 'src/lib/expert_partitioner/tree_views/*'

# FIXME: Let's consider this temporary code and be permissive with exceptions
# suppresion
Lint/HandleExceptions:
  Exclude:
    - 'src/lib/expert_partitioner/tab_views/*'
    - 'src/lib/expert_partitioner/tree_views/*'
    - 'src/lib/expert_partitioner/tree.rb'
