sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-storage-ng-image .
    # list the installed packages (just for easier debugging)
  - docker run --rm -it yast-storage-ng-image rpm -qa | sort

script:
  # the "storage-ng-travis-ruby" script is included in the base yastdevel/storage-ng image
  # see https://github.com/yast/docker-storage-ng/blob/master/storage-ng-travis-ruby
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-storage-ng-image storage-ng-travis-ruby
  - docker run -it yast-storage-ng-image rake check:doc
